{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "5258aadd_1a8ad9c1",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 1,
      "author": {
        "id": 1007976
      },
      "writtenOn": "2021-02-08T07:17:19Z",
      "side": 1,
      "message": "I would suggest to debug more on the error, it is most likely the error is for a different reason. The preferred way for virtualenv in python3 is via venv and its inbuilt, not requiring additional packages. so lets see how we can keep on using the preferred way",
      "revId": "a47da4d7346d46b76e389a7fa9157f6e7f543820",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "be4a6469_fc50e667",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 1,
      "author": {
        "id": 1008672
      },
      "writtenOn": "2021-02-08T09:44:24Z",
      "side": 1,
      "message": "Completely agree with Sanjay.\nUsing a builtin way of creating the virtualenv \"python -m venv \u003cvenv_path\u003e\" is a proffered and recommended way of creating the virtual environment.\n\nI would say as well that the reason for the failure is something else.\n\nLet\u0027s me know, if you need any help in debugging.",
      "parentUuid": "5258aadd_1a8ad9c1",
      "revId": "a47da4d7346d46b76e389a7fa9157f6e7f543820",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "ada7e749_f4a97b1b",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 1,
      "author": {
        "id": 1008484
      },
      "writtenOn": "2021-02-08T21:03:30Z",
      "side": 1,
      "message": "This patch has backwards compatibility with old openstacksdk\u003d\u003d0.39 either",
      "parentUuid": "be4a6469_fc50e667",
      "revId": "a47da4d7346d46b76e389a7fa9157f6e7f543820",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "5044f780_5db2011a",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 1,
      "author": {
        "id": 1008672
      },
      "writtenOn": "2021-02-08T22:03:04Z",
      "side": 1,
      "message": "I not sure I understand the reason to continue this patch.\nThe issue with the pip packages install failure bas been sorted in the patch - https://review.gerrithub.io/c/redhat-openstack/ansible-nfv/+/510452\n\nI have tested it on both osp 16.1 and osp 13 so we are covered for both python3 and python2 versions.",
      "parentUuid": "ada7e749_f4a97b1b",
      "revId": "a47da4d7346d46b76e389a7fa9157f6e7f543820",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "dbd982ee_49c321ee",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 1,
      "author": {
        "id": 1008484
      },
      "writtenOn": "2021-02-09T07:40:58Z",
      "side": 1,
      "message": "Main goal is stability\nSince virtualenv is more robust package then venv,\nThose errors occurred, should not pop up, unless new parameters introduced in packages or remote APIs and environment it is more stable\n\nAdditional enhancements could be: \n\nEven python2/3 environment could be created like this.\n python -m virtualenv --python\u003dpython3.6 /tmp/.ir-ci-env-py3\n python -m virtualenv --python\u003dpython2.7 /tmp/.ir-ci-env-py2\n\n\nAny way, virtualenv is supported from python3.3 why not align with standard.\n\nI wonder what others think?",
      "parentUuid": "5044f780_5db2011a",
      "revId": "a47da4d7346d46b76e389a7fa9157f6e7f543820",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "6d08537c_16390149",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1008484
      },
      "writtenOn": "2021-02-07T21:27:39Z",
      "side": 1,
      "message": "Received -1, since this fix, tends to fix gate -1\nFYI",
      "revId": "a47da4d7346d46b76e389a7fa9157f6e7f543820",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "45a56b10_856ad47a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1008484
      },
      "writtenOn": "2021-02-08T10:39:06Z",
      "side": 1,
      "message": "Please refer this\nhttps://virtualenv.pypa.io/en/stable/\n\nvenv is subset with of virtualenv, it could be installed through pip\nand could be extendable\n\nI do not know how to move on, sorry comrades \n",
      "revId": "a47da4d7346d46b76e389a7fa9157f6e7f543820",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "c0722d35_21bd1450",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1008672
      },
      "writtenOn": "2021-02-08T10:41:09Z",
      "side": 1,
      "message": "Yariv, I\u0027m not saying your fix is wrong.\nI just think it could be another issue.\nI see it on my env as well.\n\nWill look into it and update the ticket.",
      "parentUuid": "45a56b10_856ad47a",
      "revId": "a47da4d7346d46b76e389a7fa9157f6e7f543820",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "9360a296_46f33d71",
        "filename": "roles/post_install/openstack_tasks/tasks/setup_openstack_env.yml",
        "patchSetId": 1
      },
      "lineNbr": 49,
      "author": {
        "id": 1007976
      },
      "writtenOn": "2021-02-08T07:17:19Z",
      "side": 1,
      "message": "should be virtualenv",
      "range": {
        "startLine": 49,
        "startChar": 14,
        "endLine": 49,
        "endChar": 18
      },
      "revId": "a47da4d7346d46b76e389a7fa9157f6e7f543820",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "c48e4cfb_0dc93d53",
        "filename": "roles/post_install/openstack_tasks/tasks/setup_openstack_env.yml",
        "patchSetId": 1
      },
      "lineNbr": 49,
      "author": {
        "id": 1008484
      },
      "writtenOn": "2021-02-08T21:03:30Z",
      "side": 1,
      "message": "Ack",
      "parentUuid": "9360a296_46f33d71",
      "range": {
        "startLine": 49,
        "startChar": 14,
        "endLine": 49,
        "endChar": 18
      },
      "revId": "a47da4d7346d46b76e389a7fa9157f6e7f543820",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}